import openpyxl
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "四级核心词汇"
ws.append(["英文", "中文", "音标", "例句"])

words = [
    ["abandon", "放弃", "/əˈbændən/", "Don't abandon your dreams."],
    ["ability", "能力", "/əˈbɪləti/", "He has the ability to solve problems."],
    ["abroad", "在国外", "/əˈbrɔːd/", "She wants to study abroad."],
    ["absent", "缺席的", "/ˈæbsənt/", "He was absent from class today."],
    ["absorb", "吸收", "/əbˈzɔːrb/", "Plants absorb carbon dioxide."],
    ["abstract", "抽象的", "/ˈæbstrækt/", "This is an abstract concept."],
    ["abundant", "丰富的", "/əˈbʌndənt/", "The country has abundant resources."],
    ["abuse", "滥用", "/əˈbjuːs/", "Do not abuse your power."],
    ["academic", "学术的", "/ˌækəˈdemɪk/", "She has a strong academic background."],
    ["accelerate", "加速", "/əkˈseləreɪt/", "The car accelerated quickly."],
    ["access", "通道；访问", "/ˈækses/", "You have access to the library."],
    ["accompany", "陪伴", "/əˈkʌmpəni/", "I will accompany you."],
    ["accomplish", "完成", "/əˈkɑːmplɪʃ/", "He accomplished his goal."],
    ["accurate", "精确的", "/ˈækjərət/", "The data is accurate."],
    ["accuse", "控告", "/əˈkjuːz/", "He was accused of stealing."],
    ["achieve", "实现", "/əˈtʃiːv/", "She achieved her dream."],
    ["acknowledge", "承认", "/əkˈnɑːlɪdʒ/", "He acknowledged his mistake."],
    ["acquire", "获得", "/əˈkwaɪər/", "She acquired new skills."],
    ["adapt", "适应", "/əˈdæpt/", "You must adapt to changes."],
    ["adequate", "充足的", "/ˈædɪkwət/", "We have adequate time."],
    ["adjust", "调整", "/əˈdʒʌst/", "Adjust the settings."],
    ["admire", "钦佩", "/ədˈmaɪər/", "I admire your courage."],
    ["admit", "承认", "/ədˈmɪt/", "He admitted his fault."],
    ["adopt", "采纳；收养", "/əˈdɑːpt/", "They adopted a child."],
    ["advance", "前进", "/ədˈvæns/", "Technology continues to advance."],
    ["advantage", "优势", "/ədˈvæntɪdʒ/", "This gives us an advantage."],
    ["advertise", "做广告", "/ˈædvərtaɪz/", "They advertise on TV."],
    ["affect", "影响", "/əˈfekt/", "The weather affects my mood."],
    ["afford", "负担得起", "/əˈfɔːrd/", "I can afford this car."],
    ["aggressive", "侵略的", "/əˈɡresɪv/", "He has an aggressive style."],
    ["agreement", "协议", "/əˈɡriːmənt/", "We reached an agreement."],
    ["allocate", "分配", "/ˈæləkeɪt/", "We need to allocate resources."],
    ["alternative", "替代的", "/ɔːlˈtɜːrnətɪv/", "We need an alternative plan."],
    ["amaze", "使惊奇", "/əˈmeɪz/", "The view amazed me."],
    ["ambition", "雄心", "/æmˈbɪʃn/", "She has great ambition."],
    ["analyze", "分析", "/ˈænəlaɪz/", "Let me analyze the data."],
    ["announce", "宣布", "/əˈnaʊns/", "They announced the winner."],
    ["annual", "每年的", "/ˈænjuəl/", "This is the annual report."],
    ["anxiety", "焦虑", "/æŋˈzaɪəti/", "He feels anxiety about exams."],
    ["apparent", "明显的", "/əˈpærənt/", "It was apparent to everyone."],
    ["appeal", "呼吁", "/əˈpiːl/", "The idea appeals to me."],
    ["appetite", "食欲", "/ˈæpɪtaɪt/", "I have a good appetite."],
    ["appliance", "电器", "/əˈplaɪəns/", "Kitchen appliances are on sale."],
    ["application", "申请；应用", "/ˌæplɪˈkeɪʃn/", "Submit your application."],
    ["appoint", "任命", "/əˈpɔɪnt/", "He was appointed manager."],
    ["appreciate", "感激", "/əˈpriːʃieɪt/", "I appreciate your help."],
    ["approach", "方法；接近", "/əˈproʊtʃ/", "Try a different approach."],
    ["appropriate", "适当的", "/əˈproʊpriət/", "Wear appropriate clothes."],
    ["approve", "批准", "/əˈpruːv/", "The plan was approved."],
    ["arise", "出现", "/əˈraɪz/", "A problem arose."],
    ["arrange", "安排", "/əˈreɪndʒ/", "I will arrange a meeting."],
    ["article", "文章", "/ˈɑːrtɪkl/", "I read an interesting article."],
    ["aspect", "方面", "/ˈæspekt/", "Every aspect was considered."],
    ["assemble", "集合", "/əˈsembl/", "We assembled in the hall."],
    ["assess", "评估", "/əˈses/", "Let me assess the situation."],
    ["assign", "分配", "/əˈsaɪn/", "The teacher assigned homework."],
    ["assist", "帮助", "/əˈsɪst/", "Can you assist me?"],
    ["associate", "联系", "/əˈsoʊʃieɪt/", "I associate summer with beach."],
    ["assume", "假定", "/əˈsuːm/", "I assume you are right."],
    ["atmosphere", "气氛", "/ˈætməsfɪr/", "The atmosphere was friendly."],
    ["attach", "附上", "/əˈtætʃ/", "Please attach the file."],
    ["attempt", "尝试", "/əˈtempt/", "I will attempt to solve it."],
    ["attend", "参加", "/əˈtend/", "She attended the meeting."],
    ["attitude", "态度", "/ˈætɪtuːd/", "He has a positive attitude."],
    ["attract", "吸引", "/əˈtrækt/", "The show attracts many people."],
    ["authority", "权威", "/əˈθɔːrəti/", "He is an authority on history."],
    ["available", "可用的", "/əˈveɪləbl/", "The product is available."],
    ["average", "平均", "/ˈævərɪdʒ/", "The average score is 80."],
    ["avoid", "避免", "/əˈvɔɪd/", "Try to avoid mistakes."],
    ["aware", "意识到", "/əˈwer/", "I am aware of the problem."],
    ["background", "背景", "/ˈbækɡraʊnd/", "She has a strong background."],
    ["balance", "平衡", "/ˈbæləns/", "Keep a balance between work and life."],
    ["barrier", "障碍", "/ˈbæriər/", "Language is a barrier."],
    ["behave", "表现", "/bɪˈheɪv/", "Please behave yourself."],
    ["belief", "信念", "/bɪˈliːf/", "He has strong beliefs."],
    ["benefit", "利益", "/ˈbenɪfɪt/", "Exercise benefits your health."],
    ["blame", "责备", "/bleɪm/", "Don't blame others."],
    ["bother", "打扰", "/ˈbɑːðər/", "Sorry to bother you."],
    ["boundary", "边界", "/ˈbaʊndri/", "The river forms a boundary."],
    ["brilliant", "杰出的", "/ˈbrɪliənt/", "That is a brilliant idea."],
    ["budget", "预算", "/ˈbʌdʒɪt/", "We need to set a budget."],
    ["calculate", "计算", "/ˈkælkjuleɪt/", "Calculate the total cost."],
    ["campaign", "运动", "/kæmˈpeɪn/", "They launched a campaign."],
    ["capable", "有能力的", "/ˈkeɪpəbl/", "She is capable of doing it."],
    ["capacity", "容量", "/kəˈpæsəti/", "The hall has a large capacity."],
    ["capture", "捕获", "/ˈkæptʃər/", "The photo captured the moment."],
    ["career", "职业", "/kəˈrɪr/", "She has a successful career."],
    ["catalog", "目录", "/ˈkætəlɔːɡ/", "Check the product catalog."],
    ["category", "类别", "/ˈkætəɡɔːri/", "Put it in the right category."],
    ["celebrate", "庆祝", "/ˈselɪbreɪt/", "Let us celebrate together."],
    ["challenge", "挑战", "/ˈtʃælɪndʒ/", "This is a big challenge."],
    ["characteristic", "特征", "/ˌkærəktəˈrɪstɪk/", "It is a key characteristic."],
    ["charity", "慈善", "/ˈtʃærəti/", "They donated to charity."],
    ["circumstance", "环境", "/ˈsɜːrkəmstæns/", "Under such circumstances."],
    ["claim", "声称", "/kleɪm/", "He claimed he was right."],
    ["classify", "分类", "/ˈklæsɪfaɪ/", "Classify the items by type."],
    ["climate", "气候", "/ˈklaɪmət/", "The climate is changing."],
    ["coincidence", "巧合", "/koʊˈɪnsɪdəns/", "What a coincidence!"],
    ["collapse", "倒塌", "/kəˈlæps/", "The building collapsed."],
    ["colleague", "同事", "/ˈkɑːliːɡ/", "I work with my colleagues."],
    ["command", "命令", "/kəˈmænd/", "He gave a command."],
    ["comment", "评论", "/ˈkɑːment/", "Leave a comment below."],
    ["commit", "犯（罪）", "/kəˈmɪt/", "Do not commit the same mistake."],
    ["communicate", "交流", "/kəˈmjuːnɪkeɪt/", "We need to communicate better."],
    ["community", "社区", "/kəˈmjuːnəti/", "The community came together."],
    ["companion", "同伴", "/kəmˈpænjən/", "He is a good companion."],
    ["compare", "比较", "/kəmˈper/", "Compare the two options."],
    ["compete", "竞争", "/kəmˈpiːt/", "They compete for the prize."],
    ["complain", "抱怨", "/kəmˈpleɪn/", "She complained about the service."],
    ["complete", "完成", "/kəmˈpliːt/", "Please complete the form."],
    ["complex", "复杂的", "/kəmˈpleks/", "This is a complex problem."],
    ["complicate", "使复杂", "/ˈkɑːmplɪkeɪt/", "Do not complicate things."],
    ["component", "组成部分", "/kəmˈpoʊnənt/", "It is an essential component."],
    ["compose", "组成", "/kəmˈpoʊz/", "Water is composed of H2O."],
    ["comprehensive", "全面的", "/ˌkɑːmprɪˈhensɪv/", "We need a comprehensive plan."],
    ["concentrate", "集中", "/ˈkɑːnsntreɪt/", "Please concentrate on your work."],
    ["concept", "概念", "/ˈkɑːnsept/", "This is a basic concept."],
    ["concern", "关心", "/kənˈsɜːrn/", "I am concerned about you."],
    ["conclude", "得出结论", "/kənˈkluːd/", "What did you conclude?"],
    ["condition", "条件", "/kənˈdɪʃn/", "Under these conditions."],
    ["conduct", "进行", "/kənˈdʌkt/", "They conducted an experiment."],
    ["conference", "会议", "/ˈkɑːnfərəns/", "She is at a conference."],
    ["confess", "承认", "/kənˈfes/", "He confessed his guilt."],
    ["confidence", "信心", "/ˈkɑːnfɪdəns/", "I have confidence in you."],
    ["confirm", "确认", "/kənˈfɜːrm/", "Please confirm your order."],
    ["conflict", "冲突", "/ˈkɑːnflɪkt/", "They are in conflict."],
    ["confuse", "使困惑", "/kənˈfjuːz/", "Do not confuse them."],
    ["connect", "连接", "/kəˈnekt/", "Connect the two wires."],
    ["conscious", "有意识的", "/ˈkɑːnʃəs/", "He was conscious of the danger."],
    ["consequence", "后果", "/ˈkɑːnsɪkwens/", "Think about the consequences."],
    ["conservative", "保守的", "/kənˈsɜːrvətɪv/", "He holds conservative views."],
    ["consider", "考虑", "/kənˈsɪdər/", "Consider all options."],
    ["consist", "组成", "/kənˈsɪst/", "The team consists of five people."],
    ["constant", "不断的", "/ˈkɑːnstənt/", "Constant practice is key."],
    ["construct", "建造", "/kənˈstrʌkt/", "They constructed a bridge."],
    ["consult", "咨询", "/kənˈsʌlt/", "Consult the manual."],
    ["consume", "消费", "/kənˈsuːm/", "We consume too much energy."],
    ["contact", "联系", "/ˈkɑːntækt/", "Keep in contact with me."],
    ["contain", "包含", "/kənˈteɪn/", "The box contains books."],
    ["contemporary", "当代的", "/kənˈtempəreri/", "Contemporary art is diverse."],
    ["contribute", "贡献", "/kənˈtrɪbjuːt/", "She contributed to the project."],
    ["controversy", "争议", "/ˈkɑːntrəvɜːrsi/", "The issue caused controversy."],
    ["convenient", "方便的", "/kənˈviːniənt/", "This is very convenient."],
    ["convince", "说服", "/kənˈvɪns/", "I convinced him to come."],
    ["cooperate", "合作", "/koʊˈɑːpəreɪt/", "Let us cooperate."],
    ["correspond", "通信；相符", "/ˌkɔːrəˈspɑːnd/", "We correspond by email."],
    ["creative", "创造性的", "/kriˈeɪtɪv/", "She is very creative."],
    ["crisis", "危机", "/ˈkraɪsɪs/", "We are in a crisis."],
    ["criteria", "标准", "/kraɪˈtɪriə/", "What are the criteria?"],
    ["crucial", "关键的", "/ˈkruːʃl/", "This is crucial."],
    ["cultivate", "培养", "/ˈkʌltɪveɪt/", "Cultivate good habits."],
    ["curiosity", "好奇心", "/ˌkjʊriˈɑːsəti/", "Curiosity drives learning."],
    ["current", "当前的", "/ˈkɜːrənt/", "The current situation is good."],
    ["database", "数据库", "/ˈdeɪtəbeɪs/", "Check the database."],
    ["debate", "辩论", "/dɪˈbeɪt/", "They had a heated debate."],
    ["deceive", "欺骗", "/dɪˈsiːv/", "Do not deceive others."],
    ["declare", "宣布", "/dɪˈkler/", "He declared his intention."],
    ["decline", "下降；拒绝", "/dɪˈklaɪn/", "The population is declining."],
    ["decorate", "装饰", "/ˈdekəreɪt/", "They decorated the room."],
    ["decrease", "减少", "/dɪˈkriːs/", "The price decreased."],
    ["defeat", "打败", "/dɪˈfiːt/", "They defeated the enemy."],
    ["defend", "辩护", "/dɪˈfend/", "Please defend your point."],
    ["define", "定义", "/dɪˈfaɪn/", "Define this term."],
    ["definitely", "肯定地", "/ˈdefɪnətli/", "I will definitely go."],
    ["deliberate", "故意的", "/dɪˈlɪbərət/", "It was a deliberate act."],
    ["delicate", "精致的", "/ˈdelɪkət/", "The glass is delicate."],
    ["deliver", "递送", "/dɪˈlɪvər/", "Please deliver the package."],
    ["demand", "需求", "/dɪˈmænd/", "There is high demand."],
    ["demonstrate", "示范", "/ˈdemənstreɪt/", "Let me demonstrate."],
    ["deny", "否认", "/dɪˈnaɪ/", "He denied the accusation."],
    ["depart", "离开", "/dɪˈpɑːrt/", "The train departs at 6."],
    ["depend", "依赖", "/dɪˈpend/", "Do not depend on others."],
    ["deposit", "存款", "/dɪˈpɑːzɪt/", "Make a deposit at the bank."],
    ["depress", "使沮丧", "/dɪˈpres/", "The news depressed him."],
    ["derive", "源自", "/dɪˈraɪv/", "This word derives from Greek."],
    ["describe", "描述", "/dɪˈskraɪb/", "Describe what you saw."],
    ["deserve", "值得", "/dɪˈzɜːrv/", "You deserve a break."],
    ["desire", "渴望", "/dɪˈzaɪər/", "I have a desire to travel."],
    ["desperate", "绝望的", "/ˈdespərət/", "He is desperate for help."],
    ["despite", "尽管", "/dɪˈspaɪt/", "Despite the rain, we went."],
    ["destination", "目的地", "/ˌdestɪˈneɪʃn/", "We reached our destination."],
    ["determine", "决定", "/dɪˈtɜːrmɪn/", "I am determined to succeed."],
    ["develop", "发展", "/dɪˈveləp/", "The city is developing fast."],
    ["device", "设备", "/dɪˈvaɪs/", "This device is useful."],
    ["devote", "奉献", "/dɪˈvoʊt/", "She devoted her life to music."],
    ["discipline", "纪律", "/ˈdɪsəplɪn/", "You need more discipline."],
    ["discover", "发现", "/dɪˈskʌvər/", "She discovered a new star."],
    ["display", "展示", "/dɪˈspleɪ/", "The items are on display."],
    ["dispute", "争论", "/dɪˈspjuːt/", "They are in a dispute."],
    ["distinct", "明显的", "/dɪˈstɪŋkt/", "There is a distinct difference."],
    ["distinguish", "区分", "/dɪˈstɪŋɡwɪʃ/", "Can you distinguish them?"],
    ["distribute", "分配", "/dɪˈstrɪbjuːt/", "Distribute the materials."],
    ["diverse", "多样的", "/daɪˈvɜːrs/", "The group is diverse."],
    ["domestic", "国内的", "/dəˈmestɪk/", "Domestic flights are cheap."],
    ["dominate", "支配", "/ˈdɑːmɪneɪt/", "He dominates the game."],
    ["dramatic", "戏剧性的", "/drəˈmætɪk/", "There was a dramatic change."],
    ["duration", "持续时间", "/duˈreɪʃn/", "The duration is 2 hours."],
    ["dynamic", "动态的", "/daɪˈnæmɪk/", "The situation is dynamic."],
    ["economy", "经济", "/ɪˈkɑːnəmi/", "The economy is growing."],
    ["educate", "教育", "/ˈedʒukeɪt/", "Education is important."],
    ["efficient", "高效的", "/ɪˈfɪʃnt/", "This method is efficient."],
    ["eliminate", "消除", "/ɪˈlɪmɪneɪt/", "Eliminate the errors."],
    ["embrace", "拥抱", "/ɪmˈbreɪs/", "Embrace the change."],
    ["emerge", "出现", "/ɪˈmɜːrdʒ/", "New evidence emerged."],
    ["emotion", "情绪", "/ɪˈmoʊʃn/", "Control your emotions."],
    ["emphasis", "强调", "/ˈemfəsɪs/", "Put emphasis on quality."],
    ["employ", "雇用", "/ɪmˈplɔɪ/", "The company employs 100 people."],
    ["enable", "使能够", "/ɪˈneɪbl/", "This tool enables us to work faster."],
    ["encounter", "遭遇", "/ɪnˈkaʊntər/", "I encountered a problem."],
    ["enormous", "巨大的", "/ɪˈnɔːrməs/", "An enormous amount."],
    ["ensure", "确保", "/ɪnˈʃʊr/", "Ensure the safety first."],
    ["enterprise", "企业", "/ˈentərpraɪz/", "He runs a large enterprise."],
    ["entertain", "娱乐", "/ˌentərˈteɪn/", "The show entertained us."],
    ["enthusiasm", "热情", "/ɪnˈθuːziæzəm/", "She showed great enthusiasm."],
    ["entire", "全部的", "/ɪnˈtaɪər/", "The entire class passed."],
    ["environment", "环境", "/ɪnˈvaɪrənmənt/", "Protect the environment."],
    ["equivalent", "等价的", "/ɪˈkwɪvələnt/", "It is equivalent to that."],
    ["essential", "必要的", "/ɪˈsenʃl/", "Water is essential."],
    ["establish", "建立", "/ɪˈstæblɪʃ/", "We need to establish rules."],
    ["evaluate", "评价", "/ɪˈvæljueɪt/", "Evaluate the results."],
    ["evident", "明显的", "/ˈevɪdənt/", "It was evident that..."],
    ["evolve", "进化", "/ɪˈvɑːlv/", "Species evolve over time."],
    ["exaggerate", "夸张", "/ɪɡˈzædʒəreɪt/", "Do not exaggerate."],
    ["examine", "检查", "/ɪɡˈzæmɪn/", "The doctor examined him."],
    ["exceed", "超过", "/ɪkˈsiːd/", "Do not exceed the limit."],
    ["exceptional", "例外的", "/ɪkˈsepʃənl/", "She is exceptional."],
    ["excessive", "过度的", "/ɪkˈsesɪv/", "Excessive drinking is harmful."],
    ["exchange", "交换", "/ɪksˈtʃeɪndʒ/", "We exchanged ideas."],
    ["exclude", "排除", "/ɪkˈskluːd/", "Exclude irrelevant information."],
    ["execute", "执行", "/ˈeksɪkjuːt/", "Execute the plan."],
    ["exhibit", "展览", "/ɪɡˈzɪbɪt/", "The paintings are on exhibit."],
    ["expand", "扩展", "/ɪkˈspænd/", "The business expanded."],
    ["expense", "花费", "/ɪkˈspens/", "The expense is high."],
    ["expose", "暴露", "/ɪkˈspoʊz/", "Do not expose to sunlight."],
    ["extend", "延伸", "/ɪkˈstend/", "Extend the deadline."],
    ["extensive", "广泛的", "/ɪkˈstensɪv/", "Extensive research was done."],
    ["extreme", "极端的", "/ɪkˈstriːm/", "Extreme weather is common."],
]

for w in words:
    ws.append(w)

filepath = "C:/Users/Clouds/Desktop/CET4_core_words.xlsx"
wb.save(filepath)
print(f"保存成功：{len(words)} 个单词到 {filepath}")
